/* Fructus assembler tables.

   GENERATED by tools/gen-asm.js from isa/fructus.toml.  Do not edit; edit the
   spec and run `npm run binutils`.

   This file is part of the GNU Binutils.  It is free software; you can
   redistribute it and/or modify it under the terms of the GNU General Public
   License as published by the Free Software Foundation; either version 3, or
   (at your option) any later version.  */

#ifndef _FRUCTUS_ASM_H_
#define _FRUCTUS_ASM_H_

/* The form table: one row per (instruction, encoding form), sorted shortest
   first, and gas takes the first row that accepts what the programmer wrote.
   That ordering is the "prefer the smaller encoding" rule; there is no size
   search in the assembler.  */

/* How an operand is written.  FR_CC and FR_CK are the two halves of a
   condimm5, which is written as a condition and a constant in different places
   on the line - `br lt, r0, #4, target' - but encodes as one five-bit index.
   FR_CC carries that index; FR_CK only constrains which entry is chosen.  */
enum fructus_opnd_kind
{
  FR_REG,	/* r0..r7, and the spellings sp and lr */
  FR_INT,	/* an expression, which may be a symbol */
  FR_TABLE,	/* an expression that must APPEAR in a value table */
  FR_COND,	/* a cond3 name */
  FR_CC,	/* the condition half of a condimm5 */
  FR_CK		/* the constant half of a condimm5 */
};

/* Which value table an FR_TABLE operand must appear in.  "Fits" for a table
   type means "is one of these values", which drops into the same test that a
   range check provides for an ordinary integer.  */
enum fructus_valtab
{
  FR_T_NONE, FR_T_IMM3, FR_T_SHIFT3, FR_T_IMMBIT5, FR_T_IMMASK5
};

/* What a SYMBOLIC value needs.  A field too narrow to hold a whole address or
   displacement has FR_R_NONE, and a symbol therefore does not fit that form -
   the same "does it fit" test again, with no special case.  */
enum fructus_reloc
{
  FR_R_NONE, FR_R_8, FR_R_16, FR_R_8_PCREL, FR_R_16_PCREL
};

typedef struct fructus_opnd
{
  unsigned char kind;		/* enum fructus_opnd_kind */
  unsigned char table;		/* enum fructus_valtab, for FR_TABLE */
  unsigned char reloc;		/* enum fructus_reloc */
  unsigned char bits;		/* encoded width, for FR_INT */
  unsigned char is_signed;
  unsigned char pcrel;
  unsigned char swapped;	/* FR_COND: read the mirrored name set */
  signed char   tie;		/* must equal this slot, or -1 */
  signed char   fixed;		/* 1 if the form pins this operand */
  long          value;		/* the pinned value, when fixed */
} fructus_opnd;

/* Value bits -> instruction bits.  The instruction is one word with byte 0 in
   the most significant position, so emitting is a shift loop and no form
   assembles its own bytes.  */
typedef struct fructus_place
{
  unsigned char slot;
  unsigned char vlo;		/* low bit of the slice taken from the value */
  unsigned char width;
  unsigned char ilo;		/* low bit it occupies in the instruction word */
} fructus_place;

typedef struct fructus_form
{
  const char *          mnemonic;
  const char *          syntax;	/* literal text, %0..%9 for slots */
  unsigned char         nbytes;
  unsigned char         nslots;
  unsigned char         nplaces;
  unsigned long         base;	/* the fixed bits */
  const fructus_opnd *  slots;
  const fructus_place * places;
} fructus_form;

extern const fructus_form fructus_forms[];
extern const unsigned int fructus_nforms;

/* Which rows a first byte can decode to.  A list, because the mnemonic is not a
   function of byte 0: length is - the ISA commits to that - while the unary
   block packs sxt8, clz and popcount into opcode 0x32 and separates them with
   two bits of byte 1.  Each entry carries the byte-1 mask and match that
   selects it, and the first match wins.

   Printing through the row's syntax is what makes a listing reassemblable: an
   itype is a bit layout, and `ld rd, [ra, #imm3]' and `add rd, ra, #imm3'
   share one.  */
typedef struct fructus_cand
{
  unsigned char mask;		/* which bits of byte 1 select this row */
  unsigned char match;
  short         form;		/* index into fructus_forms */
} fructus_cand;

extern const fructus_cand fructus_opcode_cand[];
extern const short fructus_opcode_first[257];	/* [b] .. [b+1] is b's range */

/* The condimm5 spellings the assembler accepts: the 32 table entries, plus
   every other way of writing the same predicate.  `le #3' and `lt #4' are one
   entry; so are `hs #1' and `ne #0'.  Derived by comparing truth sets at both
   8 and 16 bits, not by a rule about +/-1.  */
typedef struct fructus_condimm
{
  const char *   cond;
  unsigned short imm;		/* as written, masked to 16 bits */
  unsigned char  index;		/* the five-bit field it encodes to */
  unsigned char  width;		/* the comparison width it holds at: 8 or 16 */
} fructus_condimm;

extern const fructus_condimm fructus_condimm_accept[];
extern const unsigned int fructus_ncondimm_accept;

/* An alias is a text rewrite: it captures each operand's text unexamined and
   builds the line the target would have been written as, then ordinary form
   selection runs on that.  No types are involved.  */
typedef struct fructus_alias
{
  const char *  mnemonic;
  const char *  syntax;		/* literal text, %0..%9 */
  unsigned char nslots;
  const char *  body;		/* the rewritten line, same %N references */
} fructus_alias;

extern const fructus_alias fructus_aliases[];
extern const unsigned int fructus_naliases;

/* Every spelling of a register and of a condition the assembler accepts, flat
   rather than indexed by encoding because the map is not one-to-one: `cs' and
   `hs' both encode as `ls'.

   A condition's `swapped' flag marks a mirrored spelling: `br gt, ra, rb, L'
   is `br lt, rb, ra, L'.  cond3 carries an operand-order bit, which is how
   twelve spellings fit into eight encodings; a form marked swapped reads only
   these and has its register places already exchanged.  */
typedef struct fructus_name
{
  const char *  name;
  unsigned char index;
  unsigned char swapped;
} fructus_name;

extern const fructus_name fructus_reg_accept[];
extern const unsigned int fructus_nreg_accept;
extern const fructus_name fructus_cond_accept[];
extern const unsigned int fructus_ncond_accept;

#endif /* _FRUCTUS_ASM_H_ */
