/* Fructus opcode table.

   GENERATED by tools/gen-opcodes.js from isa/fructus.toml.  Do not edit; edit
   the spec and run `npm run binutils`.

   This file is part of the GNU Binutils.  It is free software; you can
   redistribute it and/or modify it under the terms of the GNU General Public
   License as published by the Free Software Foundation; either version 3, or
   (at your option) any later version.  */

#ifndef _FRUCTUS_H_
#define _FRUCTUS_H_

/* Every instruction's length is a function of its first byte alone - a
   documented commitment of the ISA - so this table is flat and indexed
   directly by that byte.  An unused opcode has a NULL name and a length of
   0.  */

typedef struct fructus_opc_info_t
{
  unsigned char  length;    /* 1, 2 or 3; 0 if the opcode is unused */
  unsigned char  itype;     /* operand layout - one of the FRUCTUS_* below */
  unsigned char  pcrel;     /* 1 if its immediate is a displacement */
  const char *   name;      /* mnemonic, or NULL */
} fructus_opc_info_t;

/* pcrel is a field rather than part of the itype.  An itype is a bit layout,
   and `jmpr rel16' and `jmp abs16' have the same one: a whole opcode byte then
   a 16-bit immediate, low byte first.  What differs is what the immediate
   means, so the layouts stay one itype and the reading is recorded here.  */

extern const fructus_opc_info_t fructus_opc_info[256];

/* The operand layouts, derived from the encodings rather than named by hand.
   Two forms with the same layout share an itype even when they are different
   instructions.  */

enum fructus_itype
{
  FRUCTUS_UNUSED = 0,
  FRUCTUS_1B_NONE                = 1,
  FRUCTUS_2B_IMM3_REG_REG        = 2,
  FRUCTUS_2B_IMM5_REG            = 3,
  FRUCTUS_2B_IMMASK5_REG         = 4,
  FRUCTUS_2B_IMMBIT5_REG         = 5,
  FRUCTUS_2B_OFF8                = 6,
  FRUCTUS_2B_REG                 = 7,
  FRUCTUS_2B_REG_REG             = 8,
  FRUCTUS_2B_REG_REG_REG         = 9,
  FRUCTUS_2B_REG_REG_SHIFT3      = 10,
  FRUCTUS_3B_COND3_OFF8_REG_REG  = 11,
  FRUCTUS_3B_CONDIMM5_OFF8_REG   = 12,
  FRUCTUS_3B_IMM10_REG_REG       = 13,
  FRUCTUS_3B_IMMASK5_OFF8_REG    = 14,
  FRUCTUS_3B_IMMBIT5_OFF8_REG    = 15,
  FRUCTUS_3B_INT16               = 16,
  FRUCTUS_3B_INT16_REG           = 17
};

/* An index is not a value: byte 1 of `add rd, ra, #imm3` holds 6 where the
   programmer wrote #8.  imm3 and shift3 are the same bits read through
   different tables, which is why both are here.  */

extern const unsigned short fructus_imm3[8];
extern const unsigned short fructus_shift3[8];
extern const unsigned short fructus_immbit5[32];
extern const unsigned short fructus_immask5[32];

/* condimm5 packs a condition and a constant into five bits.  Both halves are
   needed to print one, so they come as parallel arrays.  */
extern const char * const  fructus_condimm5_cond[32];
extern const short         fructus_condimm5_imm[32];

extern const char * const  fructus_reg_names[8];
extern const char * const  fructus_cond_names[8];

#endif /* _FRUCTUS_H_ */
